services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://Lelik:89068874019@db:5432/appdb
    command: bash -c "flask db stamp head || true && python db_filling/main.py && gunicorn -b 0.0.0.0:8000 app:app"


  # Сервис базы данных
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: Lelik
      POSTGRES_PASSWORD: "89068874019"
      POSTGRES_DB: appdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Сервис для Nginx
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  db_data:
